site_name: Software Architect Docs
site_url: https://i-chetvergov.github.io/software_architect/
repo_name: i-chetvergov/software_architect
repo_url: https://github.com/i-chetvergov/software_architect

theme:
  name: material
  language: ru
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.top
  - toc.integrate
  - search.highlight
  - search
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
- admonition
- pymdownx.superfences
- pymdownx.details
- pymdownx.highlight
- pymdownx.snippets

plugins:
- search
- glightbox
- swagger-ui-tag
- enumerate-headings

nav:
- Главная: index.md

- Проект:
  - О проекте: about.md
  - Глоссарий: glossary.md

- Архитектурный кейс:
  - 1. Описание проблемы: 01_problem/index.md
  - 2. Контекст: 02_context/index.md
  - 3. Бизнес-цели: 03_business_goals/index.md
  - 4. Архитектурные драйверы: 04_arch_drivers/index.md
  - 5. Ограничения: 05_constraints/index.md
  - 6. Требования: 06_requirements/index.md
  - 7. Пользовательские сценарии: 07_use_cases/index.md
  - 8. Атрибуты качества: 08_quality_scenarios/index.md
  - 9. Архитектурное решение: 09_solution/index.md

- Диаграммы:
  - Обзор: 10_diagrams/index.md
  - C4 Контекст: 10_diagrams/c4_context.md
  - C4 Контейнеры: 10_diagrams/c4_containers.md
  - Развёртывание: 10_diagrams/deployment.md
  - Sequence: 10_diagrams/sequences.md

  - Архитектурные решения:
    - ADR: adr/index.md
    - ADR-001: adr/ADR-001.md
    - ADR-002: adr/ADR-002.md
    - ADR-003: adr/ADR-003.md
    - ADR-004: adr/ADR-004.md
    - ADR-005: adr/ADR-005.md
    - ADR-006: adr/ADR-006.md
    - ADL: adl/index.md
