# Project information
site_name: Software Architect Docs
site_url: https://i-chetvergov.github.io/software_architect/
# Repository
repo_name: i-chetvergov/software_architect
repo_url: https://github.com/i-chetvergov/software_architect

theme:
  name: material
  language: ru
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Переключить на тёмную тему
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Переключить на светлую тему
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.path
  - navigation.top
  - navigation.footer
  - navigation.indexes
  - toc.integrate
  - toc.follow
  - search
  - search.highlight
  - search.suggest
  - content.code.copy
  - content.code.annotate
  - content.tabs.link

markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- tables
- toc:
    toc_depth: 3
    permalink: true
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ""
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ""
- pymdownx.snippets

plugins:
- search
- glightbox
- swagger-ui-tag
- enumerate-headings

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/i-chetvergov/software_architect
    name: GitHub репозиторий проекта

nav:
- Главная: index.md

- Проект:
  - О проекте: about.md
  - Глоссарий: glossary.md

- Архитектурный кейс:
  - 1. Описание проблемы: 01_problem/index.md
  - 2. Контекст: 02_context/index.md
  - 3. Бизнес-цели: 03_business_goals/index.md
  - 4. Архитектурные драйверы: 04_arch_drivers/index.md
  - 5. Ограничения: 05_constraints/index.md
  - 6. Требования: 06_requirements/index.md
  - 7. Пользовательские сценарии: 07_use_cases/index.md
  - 8. Атрибуты качества: 08_quality_scenarios/index.md
  - 9. Архитектурное решение: 09_solution/index.md

- Диаграммы:
  - Обзор: 10_diagrams/index.md
  - C4 Контекст: 10_diagrams/c4_context.md
  - C4 Контейнеры: 10_diagrams/c4_containers.md
  - Развёртывание: 10_diagrams/deployment.md
  - Sequence: 10_diagrams/sequences.md

- Архитектурные решения:
  - ADL: adl/index.md
  - ADR-001: adr/ADR-001.md
  - ADR-002: adr/ADR-002.md
  - ADR-003: adr/ADR-003.md
  - ADR-004: adr/ADR-004.md
  - ADR-005: adr/ADR-005.md
  - ADR-006: adr/ADR-006.md

extra_css:
- stylesheets/extra.css
